apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: infra-devops-lab
data:
  APP_PORT: "8080"
  APP_VERSION: "dev"
  WEB_CONCURRENCY: "2"
  GUNICORN_THREADS: "2"
  LOG_LEVEL: "info"
